-- Create the Ladok schema
CREATE SCHEMA IF NOT EXISTS ladok;

-- Create the Result table with proper IDENTITY column
CREATE TABLE IF NOT EXISTS ladok.result (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personal_no VARCHAR(20) NOT NULL,
    course_id VARCHAR(50) NOT NULL,
    module_code VARCHAR(50) NOT NULL,
    grade VARCHAR(5) NOT NULL,
    exam_date DATE NOT NULL
);
